create table patients(
 ID UUID NOT NULL ,
 B_DATE VARCHAR(255) NOT NULL,
 REF_ID VARCHAR(255) NOT NULL,
 ACCESS_DATE VARCHAR(255) NOT NULL,
 ITEMS INT NOT NULL,
 MPI INT NOT NULL,
 PATIENT_TYPE_ID VARCHAR(255) NOT NULL,
 PATIENT_TYPE_TXT VARCHAR(255) NOT NULL,
 PATIENT_TYPE_REF UUID NOT NULL,
 C_DATETIME VARCHAR(255) NOT NULL,
 U_DATETIME VARCHAR(255) NOT NULL,
 PRIMARY KEY (ID)
 );