create table patient_contact(
 ID UUID NOT NULL,
 C_DATE VARCHAR(255) NOT NULL,
 CONTACT_REF VARCHAR(255) NOT NULL,
 P_CODE VARCHAR(255) NOT NULL,
 FIRST_NAME VARCHAR(255) NOT NULL,
 LAST_NAME VARCHAR(255) NOT NULL,
 USER VARCHAR(255) NOT NULL,
 FACILITY INT NOT NULL,
 CNT_REF INT NOT NULL,
 CNT_REF_2 INT NOT NULL,
 CONTACT_TYPE_ID VARCHAR(255) NOT NULL,
 CONTACT_TYPE VARCHAR(255) NOT NULL,
 CONTACT_TYPE_IDX UUID NOT NULL,
 SUMS INT NOT NULL,
 C_DATE_TIME VARCHAR(255) NOT NULL,
 U_DATE_TIME VARCHAR(255) NOT NULL,
 PRIMARY KEY (ID)
 );