drop table if exists patient_result;
drop table if exists source;

create table patient_result(
 ID UUID NOT NULL,
 B_DATE VARCHAR(255),
 REF_ID VARCHAR(255),
 ACCESS_DATE VARCHAR(255),
 ITEMS BIGINT,
 MPI BIGINT,
 PATIENT_TYPE_ID VARCHAR(255),
 PATIENT_TYPE_TXT VARCHAR(255),
 PATIENT_TYPE_REF VARCHAR(30),
 C_PATIENT_DATETIME VARCHAR(255),
 U_PATIENT_DATETIME VARCHAR(255),

 C_DATE VARCHAR(255),
 CONTACT_REF VARCHAR(255),
 P_CODE VARCHAR(255),
 FIRST_NAME VARCHAR(255) NOT NULL,
 LAST_NAME VARCHAR(255) NOT NULL,
 USER_ VARCHAR(255),
 FACILITY BIGINT,
 CNT_REF BIGINT,
 CNT_REF_2 BIGINT,
 CONTACT_TYPE_ID VARCHAR(255),
 CONTACT_TYPE VARCHAR(255),
 CONTACT_TYPE_IDX UUID,
 SUMS BIGINT,
 C_CONTACT_DATE_TIME VARCHAR(255),
 U_CONTACT_DATE_TIME VARCHAR(255),
 PRIMARY KEY (ID)
 );

 create table source (
  ID UUID DEFAULT uuid_generate_v4 (),
  FILE_NAME VARCHAR (255) NOT NULL,
  DATE_TIME VARCHAR(255) NOT NULL,
  LINE VARCHAR(255) NOT NULL,
  CLIENT_ID UUID NOT NULL ,
 PRIMARY KEY (ID)
 );
